/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jhrn' at '7/21/15 1:46 PM' with Gradle 2.5-rc-2
 *
 * @author jhrn, @date 7/21/15 1:46 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
